### ISSUE TITLE
Symbols which are enter by pressing shift are entered in spin box. Ex:- "_","<",

### ISSUE THREAD

**Issue by Sahil624** [devashishpuri/ngSpinBox#4]
Please find screenshot below.

![](https://lh3.googleusercontent.com/-WoeVi1GpyAg/XN604NEUPtI/AAAAAAAAADI/FHJjDtbHXN8RDMR4Frsbxu8p6yBHJIcwACK8BGAs/s0/Screenshot%2B%252877%2529_LI.jpg)

**Comment by devashishpuri** [comment]
Hi, thanks for opening the issue. This is resolved in v0.1.0. Please update your package.
